version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.ci
    command: dockerize -wait tcp://mysqldb:3306 -timeout 20s bash -c "php artisan migrate --seed && composer run permissions && composer test"
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7.21
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    expose:
      - 3306
